In [ ]:
                                                         #  numpy operations 

In [2]:
import  numpy as np

In [16]:
myarr = np.array([[4,2,4,5,66]]) 

In [10]:
myarr

array([ 4,  2,  4,  5, 66])

In [11]:
myarr.shape

(5,)

In [12]:
myarr.dtype

dtype('int64')

In [19]:
myarr[0, 1] =55    # changr the element on index 0,1

myarr


array([[ 4, 55,  4,  5, 66]])

In [27]:
listarray= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [28]:
listarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
listarray.dtype

dtype('int64')

In [30]:
listarray.shape

(4, 3)

In [31]:
 listarray.size

12

In [105]:
zeros=np.zeros((2,5))    #array of zeros

In [33]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
rng = np.arange(16)   #range of array

In [38]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
lspace= np.linspace(1,4,4) #it can give element of linear space

In [44]:
lspace

array([1., 2., 3., 4.])

In [45]:
emp= np.empty((4,6))  #make a empty array

In [46]:
emp

array([[2.54037962e-316, 7.01573217e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 3.16251369e+180],
       [1.05776693e-153, 6.03461190e+151, 9.89045659e-096,
        1.67772392e+243, 1.16466606e-028, 4.90900643e+252],
       [1.94918511e-153, 3.00833776e+151, 9.03292974e+271,
        6.96411098e+252, 5.49740424e-095, 3.16251369e+180],
       [3.65588338e+233, 8.61882260e+183, 2.59050147e-144,
        1.16442250e-028, 6.79769037e-310, 0.00000000e+000]])

In [70]:
arr=np.arange(99) #range on element 0 to 98

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [71]:
arr.reshape(3,33) # the multiply od=f two number is same element

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [73]:
x=[[1,2,3],[4,5,6],[5,4,6]] #ray through axix

In [77]:
ar = np.array(x)

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [5, 4, 6]])

In [80]:
ar.sum(axis=0)

array([10, 11, 15])

In [81]:
ar.sum(axis=1at)

array([ 6, 15, 15])

In [82]:
ar.T # transpose of array

array([[1, 4, 5],
       [2, 5, 4],
       [3, 6, 6]])

In [83]:
ar.flat

In [84]:
for item in ar.flat:     #it can itrate the array element
  print(item)

1
2
3
4
5
6
5
4
6


In [85]:
ar.ndim         # check the dimention 

2

In [86]:
ar.size    # size of array

9

In [88]:
ar.nbytes     #total bytes consumed by array

72

In [89]:
one = np.array([1,2,3,4,5])   #check the maximum element on index 

In [90]:
one.argmax()

4

In [92]:
one.argmin()                    #check the minimum element on index 

0

In [93]:
one.argsort()      #sort of array 

array([0, 1, 2, 3, 4])

In [94]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [5, 4, 6]])

In [95]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]])

In [98]:
ar3 = np.array([[3,4,5],
                [4,7,8],
                [2,6,8]])

In [99]:
ar3

array([[3, 4, 5],
       [4, 7, 8],
       [2, 6, 8]])

In [101]:
ar + ar3            # add of ar3 into ar

array([[ 4,  6,  8],
       [ 8, 12, 14],
       [ 7, 10, 14]])

In [102]:
ar * ar3            #multiplaction of 2 array

array([[ 3,  8, 15],
       [16, 35, 48],
       [10, 24, 48]])

In [103]:
np.sqrt(ar3)   # squr root of ar3

array([[1.73205081, 2.        , 2.23606798],
       [2.        , 2.64575131, 2.82842712],
       [1.41421356, 2.44948974, 2.82842712]])

In [104]:
                                               # Pandas Dataframe are with operation

In [106]:
import pandas as pd
import numpy as ny

In [107]:
df= pd.DataFrame({'c1':[30,31,32], 'c2':['a','b','c'], 'c3': [1,2,3]})
df


c1 c2  c3
0  30  a   1
1  31  b   2
2  32  c   3

In [108]:
df.columns              #list of the column name

Index(['c1', 'c2', 'c3'], dtype='object')

In [109]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [111]:
df['c3'].sum()   #sum of column 3

6

In [112]:
def power3(x):    #power of column
  return x**3

In [114]:
df['c3'].apply(power3)

0     1
1     8
2    27
Name: c3, dtype: int64

In [117]:
df['c1'].value_counts()  #only the value of column 1

30    1
31    1
32    1
Name: c1, dtype: int64

In [118]:
df['c1'].unique()    #unique value

array([30, 31, 32])

In [119]:
df['c1'].nunique()     #nunique value

3

In [120]:
df.sort_values(by = 'c1')  #sorting the value of column 1

c1 c2  c3
0  30  a   1
1  31  b   2
2  32  c   3

In [124]:
df= pd.DataFrame({'c1':[30,31,32,40], 'c2':['a','b','c',np.nan], 'c3': [1,np.nan,2,3]})            
df                 #nun values

c1   c2   c3
0  30    a  1.0
1  31    b  NaN
2  32    c  2.0
3  40  NaN  3.0

In [125]:
df.isnull()    # this value i all null

c1     c2     c3
0  False  False  False
1  False  False   True
2  False  False  False
3  False   True  False

In [126]:
df.dropna()

c1 c2   c3
0  30  a  1.0
2  32  c  2.0